version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      # Install Terraform
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      # Change to the Terraform directory
      - cd terraform

  build:
    commands:
      # Initialize Terraform
      - terraform init

      # Validate Terraform configuration
      - terraform validate

      # Plan Terraform deployment
      - terraform plan -out=tfplan

  post_build:
    commands:
      # Apply Terraform changes
      - terraform apply -auto-approve tfplan
